### PR TITLE
Add basic API to swirl

### PR DESCRIPTION
**Pull request by filipsch**
Hi,

Before explaining the changes that have been made to the swirl package, I want to point out very clearly that the typical swirl experience, i.e. typing `swirl()` in the R console and start learning R in R itself, is not affected whatsoever. The only thing I did was genericize some of swirl's function such that the entire package becomes more customizable and thus, usable with other technologies.

Nick informed me that the idea of having swirl work with an API already existed for a longer time. That is basically what I implemented. Wherever swirl sends output to the console, be it the `"Output"` of a new exercise, feedback, a praise or a try again message, the utility function `swirl_out()` was used. I have changed these `swirl_out()` calls with different `post_*` functions. These functions are S3 functions that have different implementations depending on the use case. If swirl is used in its original setting, `swirl_out()` is still used; when swirl is used in the DataCamp learning environment, the [swirlcamp package](https://www.github.com/Data-Camp/swirlcamp) provides alternative implementations of these S3 functions that handle the output differently. 

An example can clarify this. In the `present()` function, in `instructionSet.R`, `swirl_out()` was used to present the `"Output"` part of an exercise to the user. This function has been replaced by the `post_exercise()` function, which is defined in the new file `post.R`. There, you can see that `post_exercise.default` function still simply uses `swirl_out()`. However, if used in the DataCamp environment, the environment e, which is heavily used in swirl, will have a class "datacamp" associated, and the implementation that is available in the swirlcamp package will be used instead.

Similar things have been done for posting feedback (`post_result()`) and posting progress (`post_progress()`). 

Every time, the original code that in some places limits the flexibility of R is replaced by an S3 function with a default implementation that simply contains the original code. As such, nothing changes about the swirl experience. Only if another class is assigned to the environment e, and an alternative implementation is available in another package, will the behavior of the swirl package change.

This approach has several advantages. First, there are no unnecessary additions that are irrelevant for users that want to use swirl in R, without DataCamp. If you do a search through the proposed change of swirl, you will see that the word datacamp will appear only four times in the code. These small additions were necessary to preserve and respect the original code as much as possible. If the API-like approach that I propose here is accepted, I plan on genericizing the swirl package even further, removing any reference to datacamp. Second, alternative implementation of swirl's `post_*` functions do not have to be part of the swirl package itself. I've developed the swirlcamp package to have swirl work with DataCamp, but swirl is not aware of its existence or does not refer to swirlcamp in any way. This also allows other implementations of the `post_*` functions to live besides each other. For example, if some developers who work with swirl want to have the student's submission details sent over to an API of theirs and save the information in a database, this is perfectly possible. Finally, this new approach that makes swirl more customzable will likely make the swirl platform more attractive for teaching institutions; they can now tweak swirl according to their needs.

Another rather straightforward change was to allow alternative install locations for swirl courses. The functions in `install_course.R` were changed such that a `coursesDir` argument could be passed. If this argument is not specified, the default, original install location is used. Some functions inside `menu.R` of swirl have been changed accordingly to make sure that everything keeps working smoothly. Again, S3 functions were used, allowing different default install locations depending on the use case.

I look forward to hearing your feedback on these proposed changes.

Regards,

Filip Schouwenaars
_DataCamp_

### CODE REVIEW

**Comment by seankross** [comment]
Hi @filipsch,

Thank you for this. This pull request is probably the most significant we've ever received from someone who is not a core developer. The swirl + DataCamp integration looks awesome and we really want it to work. I won't be able to seriously interrogate your commits until the end of this week. I see that you added some functionality for where courses should be installed, we would really like to integrate [rappdirs](https://github.com/hadley/rappdirs) in order to address that issue.

**Comment by ncarchedi** [comment]
@filipsch Thanks for such a thoughtful overview. We've been tossing around the idea of a swirl API for some time now, so this provides a terrific step in the right direction.

I haven't had a chance to dive into the details of the pull request and probably won't be able to until Friday or Saturday. I look forward to it.

I'd love to hear everyone's thoughts on whether this looks acceptable to merge in its current state or if you recommend any changes/improvements prior to merging.

**Comment by ncarchedi** [comment]
I've reviewed the code. Everything looks solid to me. I'm curious to hear what everyone else thinks.

I really like how @filipsch took many of the `swirl_out`s that we had sprinkled throughout the code and consolidated them into a handful of "exit" points (see post.R). I think we should employ this strategy throughout the rest of the code so that it make it really easy for anyone (including us) to capture all swirl output and record, alter, or redirect it. @WilCrofter, @reginaastri, @seankross this goes back to our conversation at JHU many months ago (when @seankross almost passed out on us) about having single "entry" and "exit" points into/from swirl.

@filipsch I see you took advantage of the `"test"` mode infrastructure I built for compatibility with the swirlify package. That was smart. 

> If the API-like approach that I propose here is accepted, I plan on genericizing the swirl package even further, removing any reference to datacamp.

I agree with you that we should generalize this approach of "plugging into" swirl, so that we don't need to specifically mention swirlify, DataCamp, or any other tools that need to gain access to swirl's internals.

**Comment by ncarchedi** [comment]
Hey Team, anyone have a chance to look through this pull request? @seankross, @WilCrofter -- Would love to hear your thoughts. If no objections, I'll aim to merge tomorrow or Thursday.

**Comment by seankross** [comment]
I'd like to propose some changes but I won't be able to until tomorrow (Thursday).

**Comment by seankross** [comment]
@filipsch I'm working on a pull request to your pull request at Data-Camp/swirl#1. I hope to have it finished soon but things are going a little slowly over the holiday weekend.

**Comment by seankross** [comment]
Hi @ncarchedi, I'm ready for this to be merged.

**Comment by ncarchedi** [comment]
Thanks for everyone's hard work on this. Merging now.

**Pull request merged**
