### PR TITLE
Extension for template-based practice problems

### PR DESCRIPTION
**Pull request by gdancik**
This pull request includes three changes:

1) Addition of _template-based practice problems_ (currently described at https://github.com/gdancik/swirl-tbp), which allows instructors to specify question templates where values and other components are dynamically generated when the lesson is run.

2) Addition of a _rpt()_ function that allows a user to repeat the previous question or a similar question if values are dynamically generated.

3) For each question, a _HintFunction_ can be specified, which is the name of a function (provided in initLesson.R) that will be called when the user's response is not correct. This allows for more advanced hints (such as those including graphics) and hints that can be tailored based on the user's response.

An example lesson can be found here: https://github.com/gdancik/swirl-tbp/tree/swirl-tbp_example

From within R, install the lesson by typing
install_course_github("gdancik", "swirl-tbp", "swirl-tbp_example")

### CODE REVIEW

**Comment by ncarchedi** [comment]
@seankross I saw @gdancik present at useR this week. Very cool addition to swirl. Hope we can integrate into the package as a new exercise type.

**Comment by seankross** [comment]
How was useR? How did the talk go?

**Comment by gdancik** [comment]
@ncarchedi, thanks for the comment. @seankross, useR was really great. This year was my first time going since 2007 and it's great to see how much the R community has grown. There were a lot of swirl users at my talk and interest in the extension. Let me know if if you have any issues or questions on the pull request, and thanks to both of you for putting together a great package.

**Comment by gdancik** [comment]
I'm not sure what cased the travis-ci error, I will submit this again.

**Pull request closed without merging**
