### PR TITLE
wrap the parsed object with encoding

### PR DESCRIPTION
**Pull request by wush978**
#299

### CODE REVIEW

**Comment by seankross** [comment]
Thanks for this @wush978. I'll do some testing of this on my own. Is there an example yaml document you can think of off the top of your head that will break this function?

**Comment by wush978** [comment]
The Multiple choice question will produce an error now.

**Comment by wush978** [comment]
Dear @seankross ,

Sorry that I was stuck with other projects.

I guess a better way is to write some unit tests to reproduce the error I mentioned before. Therefore, I'll work on this recently and update this PR with these unit tests.

How do you think?

**Comment by wush978** [comment]
Dear @seankross ,

I correct the error and implement an unittest to address this error.

**Comment by seankross** [comment]
I'll take a look a this today.

**Comment by seankross** [comment]
@wush978 Are you still interested in merging this?

**Comment by wush978** [comment]
Yes.

Please let me know your opinions.

**Comment by seankross** [comment]
I'm going to include this in the next release of swirl. Thanks for this contribution!

**Comment by wush978** [comment]
Thanks!

**Comment by seankross** [comment]
Hi @wush978,

Can you tell me about the other features you've aded to this pull request?

**Comment by wush978** [comment]
Hi @seankross 

These changes are for my R tutorial project: https://github.com/wush978/DataScienceAndR and they are irrelevant to this PR.

It contains following changes:

- Skip hidden directories during installation
- Include the file `.initCourse.R` before .initLesson so that I put the common tests and functions of my tutorial there.
- Uninstall the course with the same name before installation

Recently I'll add more change in http://github.com/wush978/swirl such as course tracking.

**Comment by seankross** [comment]
Hi @wush978,

DataScienceAndR looks awesome! I'm so happy that you've found swirl to be useful in your classroom. 
As you can see I just merged the encoding part of this PR into the dev branch: https://github.com/swirldev/swirl/commits/dev so I'm going to close this PR. Thank you again for this contribution!

**Pull request closed without merging**
